# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c40280ec45691acb31e811a84bd2ab301210f9789713864e1106e385aa2e6c91fb2789868182a6f8ba7abcef9fb005cfcaadacc755c9893fbfdc3eeb3ce4aede

test:
  secret_key_base: 9a9826ee80ee5d7f1afce83a1167a908f49c5095fa87811dc25861dbb16b00217e6f739c38a780c47244fa698a73513bcb8716e9c5dca35c0006ffb944b82680

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
